# Generated by Django 4.0.4 on 2022-05-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_movies',
        ),
    ]
