# Generated by Django 4.0.4 on 2022-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_remove_profile_liked_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_tags',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_tags',
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_genres',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_reviews',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_desc',
            field=models.CharField(max_length=25000, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_img',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
