# Generated by Django 4.0.4 on 2022-05-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_movies_movie_rating_count_movies_movie_rating_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_reviews',
            new_name='user_ratings',
        ),
    ]
