# Generated by Django 4.0.4 on 2022-05-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_rename_user_reviews_profile_user_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_trailer_link',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
